#!/usr/bin/env python3
import subprocess
import os
import time

CACHE_TIME = 5 * 60 # seconds

def get_cache_path() -> str:
    return os.path.join(os.path.expanduser("~"), ".cache", "neofetch")


def cache_is_valid() -> bool:
    cache_path = get_cache_path()

    if not os.path.exists(cache_path):
        return False

    stat = os.stat(cache_path)

    if (time.time() - stat.st_mtime) > CACHE_TIME:
        return False

    return True


def write_cache(cache: str):
    with open(get_cache_path(), "w") as cache_file:
        cache_file.write(cache)


def read_cache() -> str:
    with open(get_cache_path(), "r") as cache_file:
        return cache_file.read()


if __name__ == "__main__":
    if cache_is_valid():
        print(read_cache())

    else:
        output: str = subprocess.run(
            ["./get-neofetch"], stdout=subprocess.PIPE
        ).stdout.decode("utf-8")
        print(output)

        write_cache(output)
