#!/usr/bin/env python3
import subprocess
import os


def get_cache_path() -> str:
    return os.path.join(os.path.expanduser("~"), ".cache", "neofetch")


def cache_exists() -> bool:
    return os.path.exists(get_cache_path())


def write_cache(cache: str):
    with open(get_cache_path(), "x") as cache_file:
        cache_file.write(cache)


def read_cache() -> str:
    with open(get_cache_path(), "r") as cache_file:
        return cache_file.read()


if __name__ == "__main__":
    if cache_exists():
        print(read_cache())

    else:
        output: str = subprocess.run(
            ["./get-neofetch"], stdout=subprocess.PIPE
        ).stdout.decode("utf-8")
        print(output)

        write_cache(output)
